services:
  banco:
    image: postgis/postgis:latest
    container_name: banco
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=apiborabora
      - POSTGRES_HOST=banco
    expose:
      - 5432
    restart: always
  
  api:
    build: .
    container_name: api
    ports:
      - "3006:3006"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=apiborabora
      - POSTGRES_HOST=banco
    expose:
      -  3006
    depends_on:
      - banco

  



